### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by yi1873** [TulsaBioinformaticsToolsmith/FASTCAR#1]
src/Runner.cpp: In member function ‘int Runner::run()’:
src/Runner.cpp:89:54: error: ‘Runner::largest_count’ is not a variable in clause ‘reduction’
Makefile:35: recipe for target 'bin/./src/Runner.o' failed
make[1]: *** [bin/./src/Runner.o] Error 1
make[1]: Leaving directory '/home/software/FASTCAR/src/cluster'
Makefile:10: recipe for target 'bin/fastcar' failed
make: *** [bin/fastcar] Error 2

**Comment by benjamin-james** [comment]
New commit should fix, confirmed to work on GCC 5.0 (Docker)

**Comment by yi1873** [comment]
@benjamin-james  FASTCAR installed successfully.  But there are some errors when I test the fastcar.           

# errors
Reading in sequences [=================================================] 100 %
K: 11
sequences read in: used memory: 51032 KB
Using 8 bit histograms
before do_run: used memory: 51032 KB
fastcar.sh: line 1: 10055 Segmentation fault      (core dumped) /usr/bin/fastcar Ecol.fa --query reads.fa --id 0.80 --output F3P2.fastcar --threads 4 --mode rc --feat fast --chunk 10000

**Comment by benjamin-james** [comment]
Can you please share the data sets you used for me to replicate this error?

**Comment by yi1873** [comment]
Send the files to you (benjamin-james@utulsa.edu) by email.  Please check it.
